version: 2

jobs:
  test:
    docker:
      - image: circleci/node:13.5.0

    steps:
      - checkout

        # Download CodeClimate reporter
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

      # Restore cache
      - restore_cache:
          keys:
            - skylab-studio-client-js-v1-{{ checksum "package.json" }}
            - skylab-studio-client-js-v1-

      - run:
          name: Install application dependencies
          command: |
            yarn

      - save_cache:
          paths:
            - ./node_modules
          key: skylab-studio-client-js-v1-{{ checksum "package.json" }}

      # Lint
      - run:
          name: Lint
          command: yarn run lint

      # Unit tests
      - run:
          name: Run unit tests
          command: |
            yarn run test:coverage
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.unit.json coverage/lcov.info

        # Upload results to CodeClimate
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.unit.json

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - staging
                - production
